apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app.kubernetese.io/name: mysql
    app.kubernetese.io/part-of: anakonda
    app.kubernetese.io/project: anakonda
    app.kubernetese.io/env: test
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: anakonda
  MYSQL_USER: anakonda
  MYSQL_PASSWORD: anakonda
