apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetese.io/name: mysql
    app.kubernetese.io/part-of: anakonda
    app.kubernetese.io/project: anakonda
    app.kubernetese.io/env: test
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetese.io/name: mysql
    app.kubernetese.io/part-of: anakonda
    app.kubernetese.io/project: anakonda
    app.kubernetese.io/env: test
  ports:
     - name: mysql
       port: 3306
